iMac Home (2)

diff --git a/zsh/utilities/backup_1_to_harddrive b/zsh/utilities/backup_1_to_harddrive
--- a/zsh/utilities/backup_1_to_harddrive
+++ b/zsh/utilities/backup_1_to_harddrive
@@ -2,7 +2,7 @@
 
 # CONFIG
 logpath_on_mac="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Backups/backups-to-external-drives.log"
-max_number_of_archives=4
+max_number_of_archives=5
 archive_every_x_months=3
 
 function do_backup {
@@ -19,10 +19,11 @@ function do_backup {
 }
 
 #───────────────────────────────────────────────────────────────────────────────
+#───────────────────────────────────────────────────────────────────────────────
 # HELPER FUNCTIONS
 
 function _pretty_header() {
-	[[ "$2" != "first" ]] && echo
+	echo
 	defaults read -g AppleInterfaceStyle &> /dev/null && fg="\e[1;30m" || fg="\e[1;37m"
 	bg="\e[1;44m"
 	[[ "$2" == "first" ]] && bg="\e[1;45m"
@@ -33,6 +34,7 @@ errors=""
 function backup() {
 	local bkp_from="$1"
 	local bkp_to="$2"
+	local short_name=${bkp_from/#$HOME/~}
 	bkp_from=$(echo "$bkp_from" | sed -E 's|/?$|/|')
 
 	if [[ ! -d "$bkp_from" ]]; then
@@ -40,13 +42,12 @@ function backup() {
 		return 1
 	fi
 	echo
-	_pretty_header "Backup: ${bkp_from/#$HOME/~}"
+	_pretty_header "Backup: $short_name"
 	mkdir -p "$bkp_to"
 
-	rsync --archive --delete --recursive --progress --human-readable \
-		--exclude="*.Trash" --exclude="*/nvim-data" --exclude=".DS_Store" \
-		"$bkp_from" "$bkp_to" ||
-		errors="$errors\nProblems occurred for: $bkp_from"
+	rsync --archive --delete --delete-excluded --recursive --progress --human-readable \
+		--exclude="*.Trash/" --exclude="*/nvim-data/" --exclude=".DS_Store" \
+		"$bkp_from" "$bkp_to" || errors="$errors\nProblems occurred for: $short_name"
 }
 
 #───────────────────────────────────────────────────────────────────────────────
@@ -82,45 +83,46 @@ backup_dest="$volume_name/Backup_$device_name"
 mkdir -p "$backup_dest"
 cd "$backup_dest" || return 1
 echo -n "Backup: $(date '+%Y-%m-%d %H:%M'), $volume_name -- " >> "$logpath_on_mac"
-# do_backup
+do_backup
 
 #───────────────────────────────────────────────────────────────────────────────
 # ARCHIVE OLDER BACKUPS
-_pretty_header "Archive of backups"
 
-archive="$volume_name/older backups"
-mkdir -p "$archive"
-cd "$archive" || return 1
-oldest_backup_date=$(command ls | tail -n1 | cut -d_ -f3)
-
-oldest_timestamp=0 # no backups yet
-[[ -n "$oldest_backup_date" ]] && oldest_timestamp=$(date -j -f "%Y-%m-%d" "$oldest_backup_date" "+%s")
-
-max_age_oldest_archive=$(date -v -${archive_every_x_months}m "+%s")
-if [[ "$oldest_timestamp" -le "$max_age_oldest_archive" ]]; then
-	echo "Oldest backup in archive more than $archive_every_x_months months old."
-	echo "Archiving current backup."
-	iso_today="$(date "+%Y-%m-%d")"
-	archive_name="Backup_${device_name}_$iso_today" # exactly 2 underscores needed
-
-	# copy via macOS Finder to leverage speed of APFS cloning
-	osascript <<- EOD
-		set currentBackup to (POSIX file "$backup_dest" as alias)
-		set archive to (POSIX file "$archive" as alias)
-
-		tell application "Finder"
-			duplicate currentBackup to folder archive
-			set name of result to "$archive_name"
-		end tell
-	EOD
-
-	# restrict number of backups
-	sleep 1
-	# shellcheck disable=2012
-	ls | tail +$((max_number_of_archives + 1)) | tr '\n' '\0' | xargs -0 rm
-else
-	echo "Oldest backup in archive is still recent (less than $archive_every_x_months months old.)"
-fi
+# _pretty_header "Archive of backups"
+#
+# archive="$volume_name/older backups"
+# mkdir -p "$archive"
+# cd "$archive" || return 1
+# oldest_backup_date=$(command ls | tail -n1 | cut -d_ -f3)
+#
+# oldest_timestamp=0 # no backups yet
+# [[ -n "$oldest_backup_date" ]] && oldest_timestamp=$(date -j -f "%Y-%m-%d" "$oldest_backup_date" "+%s")
+#
+# max_age_oldest_archive=$(date -v -${archive_every_x_months}m "+%s")
+# if [[ -n "$errors" ]] ; then
+# 	echo "Skipped, since the current backup has errors."
+# elif [[ "$oldest_timestamp" -ge "$max_age_oldest_archive" ]]; then
+# 	echo "Oldest backup in archive is still recent (less than $archive_every_x_months months old.)"
+# else
+# 	echo "Oldest backup in archive more than $archive_every_x_months months old."
+# 	echo "Archiving current backup via macOS Finder."
+# 	iso_today="$(date "+%Y-%m-%d")"
+# 	archive_name="Backup_${device_name}_$iso_today" # exactly 2 underscores needed
+#
+# 	# copy via macOS Finder to leverage speed of APFS cloning
+# 	osascript <<- EOD &> /dev/null
+# 		set currentBackup to (POSIX file "$backup_dest" as alias)
+# 		set archive to (POSIX file "$archive" as alias)
+#
+# 		tell application "Finder"
+# 			duplicate currentBackup to folder archive
+# 			set name of result to "$archive_name"
+# 		end tell
+# 	EOD
+#
+# 	# restrict number of backups
+# 	command ls -r | tail +$((max_number_of_archives + 1)) | tr '' '\0' | xargs -0 rm -rf
+# fi
 
 #───────────────────────────────────────────────────────────────────────────────
 # LOG & NOTIFY
