iMac Home (6)

diff --git a/git/nvim-hook/pre-commit b/git/nvim-hook/pre-commit
--- a/git/nvim-hook/pre-commit
+++ b/git/nvim-hook/pre-commit
@@ -1,3 +1,7 @@
 #!/usr/bin/env zsh
 
-echo "test"
+if git grep --fixed-strings --line-number "🪚" . && [[ "$PWD" != *"nvim-chainsaw"* ]]; then
+	echo
+	echo "nvim-chainsaw marker found. Aborting commit."
+	exit 1
+fi
